// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bndvrjbvfghjwwjebjvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZHZyamJ2Zmdoand3amVianZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNDMwMDcsImV4cCI6MjA4MDYxOTAwN30.1nzqpShKvovkmYn1e6IH0v0dNpWsv1g990-9Kr2X7F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});